apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-hero-server
  name: ai-hero-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai-hero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ai-hero
    spec:
      containers:
        - image: ai-hero-server:latest
          imagePullPolicy: IfNotPresent
          name: ai-hero-server
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-hero-front
  name: ai-hero-front
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:
    app: ai-hero
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000