apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-hero-api
  name: ai-hero-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai-hero-api
  strategy:
    rollingUpdaate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ai-hero-api
    spec:
      containers:
        - image: ai-hero-api
          imagePullPolicy: Never
          name: ai-hero-api
          terminationMessagePath: /dev/termination-log
          teminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminarionGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-hero-api
  name: ai-hero-api
spec:
  externalTrafficPolicy: cluster
  type: NodePort
  selector:
    app: ai-hero-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000