MIDI_NOTES_NUMBER = 128
SCALED_NOTES_RANGE = [0, 48]  # MIN, MAX
SCALED_NOTES_NUMBER = SCALED_NOTES_RANGE[1] - SCALED_NOTES_RANGE[0]
CENTRAL_NOTE_NUMBER = 60
TIME_DIVISION = 64
# TRAIN_DATA_REPLICAS = 40
NOTES_IN_OCTAVE = 12
