# possible scales
scales = {
    'major_scale': [0, 2, 4, 5, 7, 9, 11, 12],
    'minor_scale': [0, 2, 3, 4, 7, 9, 11, 12],
    'dorian_scale': [0, 2, 3, 5, 7, 9, 10, 12],
    'phrygian_scale': [0, 1, 3, 5, 7, 8, 10, 12],
    'lydian_scale': [0, 2, 4, 6, 7, 9, 11, 12],
    'mixolydian_scale': [0, 2, 4, 5, 7, 9, 10, 12],
    'aeolian_scale': [0, 2, 3, 5, 7, 8, 10, 12],
    'locrian_scale': [0, 1, 3, 5, 6, 8, 10, 12],
    'lydian_domiant_scale': [0, 2, 4, 6, 7, 9, 10, 12],
    'super_locrian_scale': [0, 1, 3, 4, 6, 8, 10, 12],
    'minor_pentatonic_scale': [0, 3, 5, 7, 10, 12],
    'major_pentatonic_scale': [0, 2, 4, 7, 9, 12],
    'minor_blues_scale': [0, 3, 5, 6, 7, 10, 12],
    'major_blues_scale': [0, 2, 3, 4, 7, 9, 12]
}
# https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies for midi keys

chords = {
    '1': [0, 4, 7],
    '2': [2],
    '3': [4],
    '4': [5, 9, 12],
    '5': [7, 11, 14],
    '6': [],
    '7': [],
    '8': [],
    '1m': [],
    '2m': [],
    '3m': [],
    '4m': [],
    '5m': [],
    '6m': [],
    '7m': [],
    '1-7': [0, 4, 7, 10],
    '2-7': [2],
    '3-7': [4],
    '4-7': [5, 9, 12, 15],
    '5-7': [7, 11, 14, 16],
    '6-7': [],
    '7-7': [],
    '8-7': [],
}

chord_names = {
    '1': 'C',
    '2': 'D',
    '3': 'E',
    '4': 'F',
    '5': 'G',
    '6': 'A',
    '7': 'B',
    '1m': 'Cm',
    '2m': 'Dm',
    '3m': 'Em',
    '4m': 'Fm',
    '5m': 'Gm',
    '6m': 'Am',
    '7m': 'Bm',
    '1-7': 'C7',
    '2-7': 'D7',
    '3-7': 'E7',
    '4-7': 'F7',
    '5-7': 'G7',
    '6-7': 'A7',
    '7-7': 'B7'
}

rhythmic_patterns = {  # define alguns padroes de onde as notas serão tocadas e onde haverão silencios
    '4': [  # 8 fusas entre tempos
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, 1, -1, -1],
        [-1, -1, -1, -1, 1, -1, -1, -1],
        [1, -1, -1, 1, -1, -1, 1, -1],
        [1, -1, -1, 1, -1, 1, -1, -1],
        [1, -1, 1, -1, -1, -1, -1, -1],
        [-1, -1, -1, 1, -1, -1, -1, -1]
    ]
}  # padroes ritmicos a cada intervalo de tempo

bass_lines = {
    'blues': [[0, 0], [4, 8], [7, 16], [9, 24], [7, 30]]  # [[nota relativa, instante que sera tocada]...]
    # 'blues': [[0, 0], [0, 8], [0, 16], [0, 24], [0, 30]] #[[nota relativa, instante que sera tocada]...]
}

known_licks = {
    # every position is a fuse and all notes are relative to the initial note. Example: [0, 1, -1, -2, -3, 3] would be [
    # 12, 13, -1, 10, 9, 15] if the initial note of the sequence is 12.
    # every phrase start on time and contains at least 8 fuses (one tempo)
    # gb g bb g c g eb g gb g
    # 6 7 10 7 12 7 15 7 6 7

    # eb-g() e-g() f-a() eb-g() e-g() c-g() g f-c d eb e-c
    'minor_blues_scale': [
        [7, -1, 10, -1, 7, -1, 12, -1],  # https://www.youtube.com/watch?v=obthFrPBN5A
        [-1, -1, -1, -1, -1, 7, -1, 15,
         16, -1, -1, -1, 12, -1, -1, -1],
        [-1, -1, -1, 10, -1, 11, -1, 12],
        [-1, -1, -1, 14, -1, 13, -1, 12],
        [3, 4, 5, -1, -1, -1, -1, 12],  # https://www.youtube.com/watch?v=obthFrPBN5A
        # [3, -1, 4, -1, 5, -1, -1, 12],  # https://www.youtube.com/watch?v=obthFrPBN5A
        # [-1, -1, -1, 3, 4, 5, -1, 12]  # https://www.youtube.com/watch?v=obthFrPBN5A
        # [-1, -1, -1, -1, -1, 7, -1, -1,
        #  15, -1, -1, 16, -1, -1, 21, -1,
        #  15, 16, -1, -1, -1, -1, 12, -1,
        #  7, 5, -1, -1, 2, -1, 3, -1],  # https://www.youtube.com/watch?v=obthFrPBN5A
        # [15, 16, 17, -1, -1, -1, -1, 24],  # https://www.youtube.com/watch?v=obthFrPBN5A
        # [7, 10, 7, 12, 7, 15, 7, 6],  # https://www.youtube.com/watch?v=obthFrPBN5A
    ]
    # 'minor_blues_scale': [
    #     [0, 1, 2, -1, -1, -1, -1, 24], # https://www.youtube.com/watch?v=obthFrPBN5A
    # ]
}

# array for conversion of note numbers into names. the position of the array is the name of the note. Ex: note_names[60] = 'C4'

note_names = [None, None, None, None, None, None, None, None, None, None, None, None,
              'cb0',
              'c0',
              'db0',
              'c#0',
              'd0',
              'eb0',
              'd#0',
              'fb0',
              'e0',
              'f0',
              'e#0',
              'gb0',
              'f#0',
              'g0',
              'ab0',
              'g#0',
              'a0',
              'bb0',
              'a#0',
              'cb1',
              'b0',
              'c1',
              'b#0',
              'db1',
              'c#1',
              'd1',
              'eb1',
              'd#1',
              'fb1',
              'e1',
              'f1',
              'e#1',
              'gb1',
              'f#1',
              'g1',
              'ab1',
              'g#1',
              'a1',
              'bb1',
              'a#1',
              'cb2',
              'b1',
              'c2',
              'b#1',
              'db2',
              'c#2',
              'd2',
              'eb2',
              'd#2',
              'fb2',
              'e2',
              'f2',
              'e#2',
              'gb2',
              'f#2',
              'g2',
              'ab2',
              'g#2',
              'a2',
              'bb2',
              'a#2',
              'cb3',
              'b2',
              'c3',
              'b#2',
              'db3',
              'c#3',
              'd3',
              'eb3',
              'd#3',
              'fb3',
              'e3',
              'f3',
              'e#3',
              'gb3',
              'f#3',
              'g3',
              'ab3',
              'g#3',
              'a3',
              'bb3',
              'a#3',
              'cb4',
              'b3',
              'c4',
              'b#3',
              'db4',
              'c#4',
              'd4',
              'eb4',
              'd#4',
              'fb4',
              'e4',
              'f4',
              'e#4',
              'gb4',
              'f#4',
              'g4',
              'ab4',
              'g#4',
              'a4',
              'bb4',
              'a#4',
              'cb5',
              'b4',
              'c5',
              'b#4',
              'db5',
              'c#5',
              'd5',
              'eb5',
              'd#5',
              'fb5',
              'e5',
              'f5',
              'e#5',
              'gb5',
              'f#5',
              'g5',
              'ab5',
              'g#5',
              'a5',
              'bb5',
              'a#5',
              'cb6',
              'b5',
              'c6',
              'b#5',
              'db6',
              'c#6',
              'd6',
              'eb6',
              'd#6',
              'fb6',
              'e6',
              'f6',
              'e#6',
              'gb6',
              'f#6',
              'g6',
              'ab6',
              'g#6',
              'a6',
              'bb6',
              'a#6',
              'cb7',
              'b6',
              'c7',
              'b#6',
              'db7',
              'c#7',
              'd7',
              'eb7',
              'd#7',
              'fb7',
              'e7',
              'f7',
              'e#7',
              'gb7',
              'f#7',
              'g7',
              'ab7',
              'g#7',
              'a7',
              'bb7',
              'a#7',
              'cb8',
              'b7',
              'c8',
              'b#7',
              'db8',
              'c#8',
              'd8',
              'eb8',
              'd#8',
              'fb8',
              'e8',
              'f8',
              'e#8',
              'gb8',
              'f#8',
              'g8',
              'ab8',
              'g#8',
              'a8',
              'bb8',
              'a#8',
              'cb9',
              'b8',
              'c9',
              'b#8',
              'db9',
              'c#9',
              'd9',
              'eb9',
              'd#9',
              'fb9',
              'e9',
              'f9',
              'e#9',
              'gb9',
              'f#9',
              'g9',
              'ab9',
              'g#9',
              'a9',
              'bb9',
              'a#9',
              'b9',
              'b#9']

note_reference = {
    'Cb': -1,
    'C': 0,
    'C#': 1,
    'Db': 1,
    'D': 2,
    'D#': 3,
    'Eb': 3,
    'E': 4,
    'E#': 5,
    'Fb': 4,
    'F': 5,
    'F#': 6,
    'Gb': 6,
    'G': 7,
    'G#': 8,
    'Ab': 8,
    'A': 9,
    'A#': 10,
    'Bb': 10,
    'B': 11,
    'B#': 12,
}
